### ISSUE TITLE
Listing 4.22 app/views/layouts/application.html.erb bootstrap

### ISSUE THREAD

**Issue by chrislerum** [rubysherpas/r4ia#17]
```
<div class="navbar-header">
      <%= link_to "Ticketee", root_path, class: "navbar-brand" %>
    </div>
    <ul class="nav navbar-nav">
      <li class="<%= "active" if current_page?("/") %>">
        <%= link_to "Home", root_path %>
</li> </ul>
```

should the ul be inside the 'navbar-header' div?

**Comment by radar** [comment]
I think I'm going to defer this one to @sevenseacat.

**Comment by sevenseacat** [comment]
No, it shouldn't. See the examples in the Bootstrap docs at http://getbootstrap.com/components/#navbar-default

The `navbar-header` div is pretty much for the header you would see in a small responsive view, eg. the site name/logo and the hamburger menu. We haven't used a lot of the specific responsive styles, which will be rectified shortly, but for now, this is fine as is :)
