### ISSUE TITLE
need to restart spring in chapter 6.2

### ISSUE THREAD

**Issue by chrislerum** [rubysherpas/r4ia#18]
after installing devise, where we add the following snippet:

```
<li class="<%= "active" if current_page?("/users/sign_up") %>">
  <%= link_to "Sign up", new_user_registration_path %>
</li>
```

we get:

Failure/Error: click_link "Sign up"
     ActionView::Template::Error:
       undefined method `registration_path' for #<#Class:0x007fccd632be78:0x007fccd63228a0>

restarting spring makes all happy again.

**Comment by sevenseacat** [comment]
Spring :hammer:

**Comment by radar** [comment]
@chrislerum Do you have a stacktrace for that error please?

**Comment by chrislerum** [comment]
no, may as well close this as a fluke
