### ISSUE TITLE
6.3 error when setting up warden's login_as method

### ISSUE THREAD

**Issue by chrislerum** [rubysherpas/r4ia#19]
￼config.after(type: :feature) { Warden.test_reset! }

gives me:

ticketee/spec/rails_helper.rb:12:in `block in <top (required)>': undefined local variable or method`￼config' for main:Object (NameError)

**Comment by radar** [comment]
Can you please show us the full context of where you're putting this line in the file?

**Comment by chrislerum** [comment]
it was in rspec config, but can close this as it was resolved by restarting spring.

—

**Comment by radar** [comment]
I have doubt that it was in the correct block. You wouldn't be getting that error if it was in the block.
