### ISSUE TITLE
7.1.1 unnecessary rake db:test:prepare

### ISSUE THREAD

**Issue by chrislerum** [rubysherpas/r4ia#20]
7.1.1 has:

Run bin/rake db:migrate and bin/rake db:test:prepare now

but there's no longer any need of db:test:prepare, as stated earlier in the book

**Comment by radar** [comment]
I suspect this is because Chapter 7 has not been updated on the Manning copy of the book. In my text I don't have any mention of `rake db:test:prepare`.
