### ISSUE TITLE
Pundit policy generated file does not exist

### ISSUE THREAD

**Issue by biophysicsguy** [rubysherpas/r4ia#22]
8.1.4 refers to a generated spec called 'spec/policies/post_policy_spec.rb'.  A file by that name is not generated or found in any of the GitHub branches for the ticketee project (chapter 8-2 or chapter 9) nor is it referred to in the rest of the chapter.  The text should be modified slightly to say 

"create a new file called 'spec/policies/project_policy_spec.rb' and add the following content:"

(at which point the permissions block in Listing 147 should be added)

**Comment by sevenseacat** [comment]
Ah good catch - the Pundit generator does generate a file called `project_policy_spec.rb`, so I'll fix the incorrect filename listed here.
