### ISSUE TITLE
Chapter 10.8.3 V17

### ISSUE THREAD

**Issue by axelkanakan** [rubysherpas/r4ia#5]
Went into the rails console and did

user = User.create!(email: "test@example.com", password: "password")
user.save #because confirm! and confirm were not defined and finally when i did

user.permissions.create({thing: Project.first, action: "view"}, without_protection: true)

i got the error 
ArgumentError: wrong number of arguments (2 for 0..1) so not sure what wrong... 

here's my github: https://github.com/krillencoder/ticketee

**Comment by radar** [comment]
Hi @krillencoder, `:without_protection` has been removed in Rails 4. What I suspect has happened is that this section in Chapter 10 hasn't been updated to remove that option. 

We'll fix it up once we get to the review for that chapter. Thanks for letting us know about it.

**Comment by radar** [comment]
Actually this was easy enough to fix without waiting for the review. I've done that just now.

**Comment by axelkanakan** [comment]
Okay I omitted the without_protection part, and the reason it wasn't saving the user was because i didn't add the password_confirmation. Thank you
