### ISSUE TITLE
Chapter 10.33 V17 "bin/rspec fails" 

### ISSUE THREAD

**Issue by axelkanakan** [rubysherpas/r4ia#7]
Got bin/rspec spec/controllers/comments_controller_spec.rb to pass
but bin/rspec comes back with the error 

1) Assigning permissions Changing states for a ticket
Failure/Error: within("#ticket .state") do
Capybara::ElementNotFound:
Unable to find css "#ticket .state"

this only happened after I added the "if cannot?" code in the comment controller.
Not sure what to change here...

**Comment by radar** [comment]
Could you include a link to your repo on GH too please?

**Comment by axelkanakan** [comment]
https://github.com/krillencoder/ticketee

**Comment by radar** [comment]
@krillencoder I cloned the repo tonight and was unable to see any errors:

```
75 examples, 0 failures
```

Have you fixed this problem? If so, was it a problem with the book?

**Comment by axelkanakan** [comment]
I 'm still struggling with it, I just pushed it again to make sure.

**Comment by radar** [comment]
I can verify this issue exists in your repo now. I will see what the cause of it is.

**Comment by axelkanakan** [comment]
Thank you, I'll keep troubleshooting too

**Comment by radar** [comment]
Quite a rather tricky one to track down... but we got there in the end.

The problem with this is the code in `SessionsController` of all things. It does this:

```
user = User.where(:name => params[:signin][:name]).first
```

The `user_factory` code creates both users and admins with the same name ("username")... which means that there's two users with the name "username", an admin and a normal user. The code selects the admin user which _doesn't_ have the explicit permission to change states of a ticket, and therefore once that user is signed in they can't change the state.

Ultimately this comes down to the code from Chapter 6 which built the authentication part of your application. I've recently rewritten this chapter to improve the authentication code. This chapter hasn't been published yet, but I believe the code in the chapter will fix your problem.

You can fix this by changing the `user_factory` code to generate unique usernames for the users:

```
sequence(:name) { |n| "username#{n}" }
```

Although I would probably advise you to go through Chapter 6 again once it has been published.

Very sorry that this code was not up to snuff.

**Comment by axelkanakan** [comment]
Do you know when it'll be published?

**Comment by axelkanakan** [comment]
Nevermind I got to pass thanks for the help

**Comment by radar** [comment]
No timeframe on the publication at the moment as it relies on a large number of factors. Should be by Christmas :)

**Comment by zarapustra** [comment]
Thanks, man. It was very helpful for me
